services:
  postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - postgres
  rustfs:
    image: "rustfs/rustfs:latest"
    environment:
      RUSTFS_ACCESS_KEY: asdfasdf
      RUSTFS_SECRET_KEY: asdfasdf
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_CONSOLE_ENABLE: true
    volumes:
      - rustfs:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres:
  rustfs:
